name: Auto Label New Issues

on:
  issues:
    types: [opened]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Auto Label
        uses: dataquest-dev/gh-actions/start@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
